#!/usr/bin/env node
/**
 * StarForge conformance gates.
 *
 *     npm install          # once - pins the compiler exactly
 *     npm run gates
 *
 * -- WHAT IT DOES -------------------------------------------------------------
 * 1. Structural gates over the real source tree (no network, config coherence).
 * 2. Discovers every `.ts` at the package root and typechecks the lot under
 *    `--strict --noEmitOnError`.
 * 3. Discovers every `*.conformance.ts` and runs them all, aggregating results.
 *
 * -- WHY IT DISCOVERS RATHER THAN LISTS ----------------------------------------
 * The previous revision hardcoded three filenames and ten stubs. A module added
 * later was therefore silently OUTSIDE the gates: typechecked in nobody's build,
 * its conformance suite run only if someone remembered. `densityMap` sat in
 * exactly that position, reported green on the strength of an ad-hoc compile the
 * harness never performed.
 *
 * Discovery removes the failure mode instead of documenting it. Add a module and
 * it is typechecked. Add `<module>.conformance.ts` and it runs. Nothing to
 * remember, and no list to fall out of date.
 *
 * -- STUBS ----------------------------------------------------------------------
 * `types.ts` imports taxonomies from modules that do not exist yet, so those get
 * THROWAWAY STUBS - but ONLY where the real file is absent. A stub is never
 * written over a real module, so stubs retire themselves one at a time as the
 * build progresses. Everything lands in a disposable `.gate-tmp/`, never in the
 * package tree: a stub sitting beside a real module is exactly what gets mistaken
 * for a source of truth.
 *
 * -- TOOLCHAIN (correction C11) -------------------------------------------------
 * A local `typescript` is preferred; the fallback pins an EXACT version rather
 * than taking whatever npx finds newest. The flag set - `--module commonjs`, no
 * `--moduleResolution`, no `--ignoreDeprecations` - is verified green under
 * TypeScript 5.9.3, 6.0.3 and 7.0.2. The compiler version prints with the
 * results: a gate outcome without its toolchain recorded is the same defect as a
 * catalogue number without its retrieval date.
 */
const fs = require('fs');
const path = require('path');
const { execSync, execFileSync } = require('child_process');

/** Exact fallback if no local `typescript` is installed. Bump deliberately. */
const PINNED_TS = '6.0.3';

/** Compiler flags. `tsconfig.json` MUST mirror these - gate S2 asserts it. */
const TSC_FLAGS = { strict: true, noEmitOnError: true, target: 'ES2020', module: 'commonjs' };
const TSC_FLAG_STRING = Object.entries(TSC_FLAGS)
  .map(([k, v]) => (v === true ? `--${k}` : `--${k} ${v}`)).join(' ');

const HEADER = '// THROWAWAY STUB - generated by verification/run-gates.js.\n' +
               '// NOT a source of truth. Not part of the package. Do not copy from this file.\n';

/** Minimal shapes, used ONLY where the real module is absent. */
const STUBS = {
  'stellarProperties.ts': "export type StellarClass = 'G2V'|'M5V';\nexport type StarKind = StellarClass | 'white-dwarf';\n",
  'stellarHistory.ts': "export type RotationClass = 'slow'|'fast';\nexport type ActivityClass = 'flare-active'|'moderate'|'quiet';\n",
  'multiplicity.ts': "export type BinaryRegime = 'single'|'s-type'|'p-type';\n",
  'planets.ts': "export type PlanetClass='rocky'; export type PlanetSubclass='terran'; export type EnvelopeState='primary-retained'|'stripped'; export type OrbitType='s-type'|'p-type'; export type PlanetZone='A'|'B'|'C';\n",
  'belts.ts': "export type BeltComposition='icy'; export type BeltKind='main';\n",
  'moons.ts': "export type MoonComposition='rock'; export type MoonSense='prograde'; export type MoonOrigin='accretion';\n",
  'atmosphere.ts': "export type AtmosphereKind='none'; export type CloudClass='water'; export type PressureClass='thin';\n",
  'biosphere.ts': "export type BiosphereLevel='none'; export type SignatureVerdict='none'; export type SignatureOrigin='biotic'|'abiotic'|'engineered';\n",
  'terraforming.ts': "export type TerraformType='atmospheric'; export type Completeness='partial';\n",
  'humanHabitability.ts': "export type HabTier = 0|1|2|3|4;\nexport type SupportLevel = 'none'|'shelter'|'unassisted';\n",
};

/** At least these must be present for the tree to mean anything. */
const REQUIRED = ['types.ts', 'galaxyModel.ts'];

const SCAN_EXT = new Set(['.ts', '.tsx', '.js', '.mjs', '.cjs']);
const SCAN_SKIP = new Set(['verification', 'node_modules', '.gate-tmp', 'build', 'dist', '.git']);

/* ----------------------------- locate the tree --------------------------- */

function findRoot() {
  for (const dir of [__dirname, path.resolve(__dirname, '..'), process.cwd()]) {
    if (REQUIRED.every((f) => fs.existsSync(path.join(dir, f)))) return dir;
  }
  return null;
}

const ROOT = findRoot();
if (!ROOT) {
  console.error(
    `MISSING: could not find [${REQUIRED.join(', ')}] beside this script.\nLooked in:\n` +
    `  ${__dirname}\n  ${path.resolve(__dirname, '..')}\n  ${process.cwd()}`);
  process.exit(2);
}
const TMP = path.join(ROOT, '.gate-tmp');

/* ------------------------- structural gates (pre-flight) ------------------ */

let structuralFailures = 0;
function structural(label, ok, detail) {
  if (ok) { console.log(`ok    ${label}`); return; }
  structuralFailures++;
  console.error(`FAIL  ${label}`);
  for (const line of detail ?? []) console.error(`      ${line}`);
}

function walkSource(dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) { if (!SCAN_SKIP.has(entry.name)) walkSource(full, acc); }
    else if (SCAN_EXT.has(path.extname(entry.name))) acc.push(full);
  }
  return acc;
}

/**
 * Remove comments while PRESERVING string contents. Naive `//`-to-end-of-line
 * stripping would eat the `//` out of a URL inside a string literal, which is
 * precisely backwards. A regex literal containing `//` may cause a false
 * positive; that fails safe.
 */
function stripComments(src) {
  let out = '', i = 0, quote = null;
  while (i < src.length) {
    const c = src[i], d = src[i + 1];
    if (quote) {
      if (c === '\\') { out += c + (d ?? ''); i += 2; continue; }
      if (c === quote) quote = null;
      out += c; i++; continue;
    }
    if (c === '"' || c === "'" || c === '`') { quote = c; out += c; i++; continue; }
    if (c === '/' && d === '/') { while (i < src.length && src[i] !== '\n') i++; continue; }
    if (c === '/' && d === '*') { i += 2; while (i < src.length && !(src[i] === '*' && src[i + 1] === '/')) i++; i += 2; out += ' '; continue; }
    out += c; i++;
  }
  return out;
}

/**
 * GATE S1 - the plugin makes no network calls.
 *
 * A runtime fetch breaks four laws at once: generation must be pure and
 * reproducible from (worldSeed, sysid, genVersion); modules are pure functions of
 * an rng and their inputs; a vault depending on a remote service has not survived
 * the plugin; and two users on one seed and one genVersion must get one galaxy.
 *
 * `verification/` is EXCLUDED and must stay excluded - the tools in it query TAP
 * services deliberately, at spec time, on a human's machine. That exclusion IS
 * the distinction the gate protects: a constant is fetched ONCE by a person,
 * frozen into a module with its retrieval date, thereafter as inert as pi.
 *
 * COMMENTS ARE STRIPPED FIRST. Provenance headers cite DOIs and service URLs by
 * law (S1, rule 3), so a naive text search would fire on the very thing the
 * project requires. Only code is scanned.
 */
const BANNED_TOKENS = [
  ['fetch(', 'fetch()'], ['requestUrl', "Obsidian's requestUrl"],
  ['XMLHttpRequest', 'XMLHttpRequest'], ['WebSocket', 'WebSocket'],
  ['EventSource', 'EventSource'], ['sendBeacon', 'navigator.sendBeacon'],
  ['node-fetch', 'node-fetch'], ['axios', 'axios'],
];
const BANNED_MODULES = /(?:from|require\s*\()\s*['"](?:node:)?(https?|net|dns|tls|dgram)['"]/;
const URL_LITERAL = /https?:\/\//;

function gateNoNetwork() {
  const bad = [];
  for (const file of walkSource(ROOT)) {
    stripComments(fs.readFileSync(file, 'utf8')).split('\n').forEach((line, n) => {
      const at = `${path.relative(ROOT, file)}:${n + 1}`;
      for (const [tok, label] of BANNED_TOKENS) if (line.includes(tok)) bad.push(`${at}  ${label}`);
      if (BANNED_MODULES.test(line)) bad.push(`${at}  network module import`);
      if (URL_LITERAL.test(line)) bad.push(`${at}  URL literal in code`);
    });
  }
  structural('S1 plugin source makes no network calls', bad.length === 0,
    [...bad, '', 'Generation must be pure and reproducible from the seed alone.',
     'If this is a spec-time tool rather than plugin code, it belongs in',
     'verification/, which is excluded from this scan.']);
}

/**
 * GATE S2 - `tsconfig.json` mirrors the gate flags.
 *
 * Without it the editor and the gates can disagree, and "it compiles for me"
 * against a red build is a long, stupid afternoon. The gate flags are the truth;
 * tsconfig exists so an editor reports the same diagnostics.
 */
function gateConfigCoherence() {
  const p = path.join(ROOT, 'tsconfig.json');
  if (!fs.existsSync(p)) {
    structural('S2 tsconfig.json mirrors the gate flags', false,
      ['tsconfig.json is absent. Editors will apply their own defaults and',
       'silently disagree with the gates. Add one mirroring:', `  ${TSC_FLAG_STRING}`]);
    return;
  }
  let opts;
  try {
    opts = JSON.parse(fs.readFileSync(p, 'utf8').replace(/^\s*\/\/.*$/gm, '')).compilerOptions ?? {};
  } catch (e) {
    structural('S2 tsconfig.json mirrors the gate flags', false, [`unparseable: ${e.message}`]);
    return;
  }
  const wrong = Object.entries(TSC_FLAGS)
    .filter(([k, v]) => String(opts[k]).toLowerCase() !== String(v).toLowerCase())
    .map(([k, v]) => `${k}: tsconfig has ${JSON.stringify(opts[k])}, gates use ${JSON.stringify(v)}`);
  structural('S2 tsconfig.json mirrors the gate flags', wrong.length === 0, wrong);
}

gateNoNetwork();
gateConfigCoherence();
if (structuralFailures > 0) {
  console.error(`\nGATES FAILED - ${structuralFailures} structural.`);
  process.exit(1);
}

/* ----------------------------- discover and stage ------------------------- */

const rootTs = fs.readdirSync(ROOT).filter((f) => f.endsWith('.ts')).sort();
const suites = rootTs.filter((f) => f.endsWith('.conformance.ts'));
const stubbed = Object.keys(STUBS).filter((f) => !rootTs.includes(f)).sort();
const retired = Object.keys(STUBS).filter((f) => rootTs.includes(f)).sort();

fs.rmSync(TMP, { recursive: true, force: true });
fs.mkdirSync(TMP, { recursive: true });
for (const name of stubbed) fs.writeFileSync(path.join(TMP, name), HEADER + STUBS[name]);
for (const name of rootTs) fs.copyFileSync(path.join(ROOT, name), path.join(TMP, name));

/**
 * Filesystem-based, because TypeScript 7 ships an `exports` map that blocks the
 * `typescript/bin/tsc` subpath - module resolution would silently push a
 * perfectly good local install onto the network fallback.
 */
function resolveTsc() {
  const seen = new Set();
  for (const start of [ROOT, __dirname, process.cwd()]) {
    let dir = start;
    for (;;) {
      if (!seen.has(dir)) {
        seen.add(dir);
        const pkgDir = path.join(dir, 'node_modules', 'typescript');
        const bin = path.join(pkgDir, 'bin', 'tsc');
        const meta = path.join(pkgDir, 'package.json');
        if (fs.existsSync(bin) && fs.existsSync(meta)) {
          const cmd = `node ${JSON.stringify(bin)}`;
          // PROVE it runs before trusting it. TypeScript 7 ships its compiler as
          // a platform-specific native sub-package, so a partial or cross-platform
          // install has bin/tsc present and the executable missing - and the
          // resulting stack trace reads like a bug in this project rather than a
          // broken node_modules. One --version call converts that into a sentence.
          try {
            execSync(`${cmd} --version`, { stdio: 'pipe' });
            return { cmd, version: JSON.parse(fs.readFileSync(meta, 'utf8')).version,
                     source: `local: ${pkgDir}` };
          } catch {
            console.warn(`warn:  local typescript at ${pkgDir} is present but will not run`);
            console.warn(`       (incomplete install?) - falling back to the pinned ${PINNED_TS}`);
          }
        }
      }
      const up = path.dirname(dir);
      if (up === dir) break;
      dir = up;
    }
  }
  // `--package=` is required: `npx --yes typescript@X tsc` treats `tsc` as an
  // argument to the package's default binary, not as the binary itself.
  return { cmd: `npx --yes --package=typescript@${PINNED_TS} tsc`,
           version: PINNED_TS, source: `npx, pinned ${PINNED_TS}` };
}

const tsc = resolveTsc();
console.log(`\nroot:   ${ROOT}`);
console.log(`tsc:    ${tsc.version} (${tsc.source})`);
console.log(`source: ${rootTs.length} file(s), ${suites.length} conformance suite(s)`);
console.log(`stubs:  ${stubbed.length} still needed` +
  (stubbed.length ? ' - ' + stubbed.map((f) => f.replace('.ts', '')).join(', ') : ''));
if (retired.length) {
  console.log(`        ${retired.length} retired (real module present): ` +
    retired.map((f) => f.replace('.ts', '')).join(', '));
}

/* --------------------------------- typecheck -------------------------------- */

// A GENERATED config, not a flag list. TypeScript 6+ raises TS5112 when files
// are named on the command line while any tsconfig.json is visible up the tree -
// and the root one always is, because .gate-tmp/ lives inside the package. Both
// this config and the root one are built from TSC_FLAGS, so there is still
// exactly one source of truth for the flags and gate S2 still compares against it.
// `types: ['node']` is needed because a handful of Stage-9 conformance
// suites do their own structural grep gates (S9: "grep for isHumanHabitable",
// "grep for Rossby-number computation") by reading sibling .ts sources with
// `fs`/`path`/`__dirname` - real Node builtins, not part of the plugin
// runtime surface itself (gate S1 already bans plugin *source* from touching
// the network; reading a local sibling file to grep it is neither a network
// call nor plugin-shipped behaviour). Without an explicit `types` array,
// automatic @types inclusion is inconsistent across TypeScript majors in an
// isolated build directory like `.gate-tmp/`.
fs.writeFileSync(path.join(TMP, 'tsconfig.json'), JSON.stringify({
  compilerOptions: { ...TSC_FLAGS, outDir: './build', skipLibCheck: true, types: ['node'] },
  include: rootTs.concat(stubbed),
}, null, 2));

try {
  execSync(`${tsc.cmd} -p .`, { cwd: TMP, stdio: 'inherit' });
} catch {
  console.error('\nTYPECHECK FAILED - the gates did not run.');
  process.exit(1);
}
console.log(`typecheck: clean, ${rootTs.length} file(s) (tsc ${tsc.version})\n`);

/* ---------------------------- run every suite ------------------------------ */

if (suites.length === 0) {
  console.error('NO CONFORMANCE SUITES FOUND. Expected at least one *.conformance.ts.');
  process.exit(1);
}

const failed = [];
for (const suite of suites) {
  console.log(`-- ${suite} --`);
  try {
    execFileSync('node', [path.join('build', suite.replace(/\.ts$/, '.js'))],
      { cwd: TMP, stdio: 'inherit' });
  } catch { failed.push(suite); }
  console.log('');
}

if (failed.length) {
  console.error(`GATES FAILED in: ${failed.join(', ')}`);
  process.exit(1);
}
console.log(`all ${suites.length} suite(s) passed, plus 2 structural gates`);
console.log(`(toolchain: TypeScript ${tsc.version} - record this beside any gate result)`);
console.log(`(scratch: ${TMP} - safe to delete)`);
